<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    //get only available products

    public function findAvailableProducts()
    {
        return $this->_em->createQuery('SELECT u FROM AppBundle\Entity\Product u WHERE u.quantity > 0')
            ->getResult();
    }


}
