<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    //get only available products with category

    public function findAvailableProducts($category_id = null)

    {

        if ($category_id == null) {

            $qb = $this->_em->createQuery('SELECT u FROM AppBundle\Entity\Product u WHERE u.quantity > 0 AND u.forsale = 1');

            return $qb->getResult();
        } else

        $qb = $this->_em->createQuery('SELECT u FROM AppBundle\Entity\Product u WHERE u.quantity > 0 AND u.category = :category AND u.forsale = 1')
            ->setParameter('category',  $category_id );

        return $qb->getResult();
    }


}
